
name: CI
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install assertpy PyHamcrest nose2
      - name: Run tests
        run: |
            nose2
            
version: 2.1
orbs:
  codecov: codecov/codecov@3.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install assertpy PyHamcrest nose2 coverage
      - run:
          name: Run tests and collect coverage
          command: |
            coverage run tests/test_school_diary.py
            coverage run tests/test_school_subject.py
            coverage run tests/test_student.py
            coverage xml
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build
            