
name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
           pip install -r requirements.txt
      - name: Run tests
        run: |
            nose2 --with-coverage
            coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
            fail_ci_if_error: true
            token: ${{ secrets.CODECOV_TOKEN }}